# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inicio"
  url = "#about"
  weight = 10

[[main]]
  name = "Noticias"
  url = "/noticia"
  weight = 20

[[main]]
  identifier = "informe"
  name = "Informes"
  url = "/informe"
  weight = 30

[[main]]
  identifier = "mesasocial"
  name = "Mesa Social"
  url = "#projects"
  parent = "informe"
  weight = -30

[[main]]
  identifier = "participantes"
  name = "Participantes"
  url = "/informe/participante"
  parent = "informe"
  weight = 30

[[main]]
    identifier = "metodologico"
    name = "Metodológico"
    url = "/informe/metodologico"
    parent = "informe"
    weight = 40

[[main]]
  identifier = "publicaciones"
  name = "Publicaciones"
  url = "#projects"
  weight = 30

[[main]]
  name = "Sintomas"
  url = "#projects"
  weight = -30
  parent = "publicaciones"

[[main]]
  name = "Prácticas Sociales"
  url = "#projects"
  weight = 30
  parent = "publicaciones"


[[main]]
  identifier = "somos"
  name = "Quienes somos"
  url = "/somos"
  weight = 40

[[main]]
  name = "Sobre MOVID"
  url = "/somos/sobre"
  weight = 1
  parent = "somos"

[[main]]
  name = "Instituciones"
  url = "/somos/instituciones"
  weight = 2
  parent = "somos"

[[main]]
  name = "Equipo"
  url = "/somos/equipo"
  weight = 3
  parent = "somos"

[[main]]
  name = "MOVID-App"
  url = "/app"
  weight = 60

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
